#!/bin/bash

paths=(
        "/lib/x86_64-linux-gnu/libudev.so.1" # Ubuntu, Xubuntu, Mint
        "/usr/lib64/libudev.so.1" # SUSE, Fedora
        "/usr/lib/libudev.so.1" # Arch, Fedora 32bit
        "/lib/i386-linux-gnu/libudev.so.1" # Ubuntu 32bit
    )
for i in "${paths[@]}"
do
    if [ -f $i ] ; then
      dirpath=$(dirname $i)
        if [ ! -e $dirpath/libudev.so.0 ] ; then
            sudo ln -sf "$i" $dirpath/libudev.so.0
        fi
      echo "create link succefull "
      break
    fi
done
