#!/bin/sh
# postinst script 
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package
#

echo Create soft link...
webdePath=/usr/share/webde
appPath=$webdePath/app

for appName in `ls $appPath`
do
  cd $appPath/$appName
  ln -s ../../sdk/lib lib
done

#echo Initialize webde...
#bash $webdePath/init/init_rio.sh 
#bash $webdePath/init/init_database.sh clean 

exit 0


